"use client";

import { Bot, Goal, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { healthProgress, healthStreaks, healthSuggestions, healthSummaries } from "@/lib/dummy-data";
import { useAppStore } from "@/stores/app-store";
import { ListItem, Progress, RangeToolbar, ViewFrame } from "@/components/dashboard/shared";

export function HealthScreen() {
  const openEntry = useAppStore((state) => state.openEntry);
  const openGoal = useAppStore((state) => state.openGoal);
  const openAgent = useAppStore((state) => state.openAgent);
  const openDetail = useAppStore((state) => state.openDetail);

  return (
    <ViewFrame>
      <RangeToolbar domain="health" />
      <div className="grid gap-4 xl:grid-cols-3">
        <Card>
          <CardHeader><div><CardTitle>Nutrition progress</CardTitle><CardDescription>Calories and protein against daily goals.</CardDescription></div></CardHeader>
          <div className="flex flex-wrap items-center gap-4">
            <div className="ring-progress grid h-28 w-28 place-items-center rounded-full text-2xl font-black">74%</div>
            <div className="grid min-w-60 flex-1 gap-3">{healthProgress.map((item) => <ListItem key={item.title} {...item} action={<strong>{item.value}</strong>} />)}</div>
          </div>
        </Card>
        <Card>
          <CardHeader><div><CardTitle>Streaks</CardTitle><CardDescription>Habit consistency preview.</CardDescription></div></CardHeader>
          <div className="grid gap-3">{healthStreaks.map((item) => <ListItem key={item.title} title={item.title} meta={item.meta} tone={item.tone} badge={item.badge} />)}</div>
        </Card>
        <Card>
          <CardHeader><div><CardTitle>Health recommendation</CardTitle><CardDescription>Generated by the future Health Agent.</CardDescription></div></CardHeader>
          <p className="text-sm leading-6 text-muted-foreground">Dinner should prioritize protein with moderate carbs. A simple chicken bowl or paneer salad would keep calories controlled while closing the protein gap.</p>
        </Card>
      </div>
      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="grid gap-4">
          <div><span className="small-label">Active health goal</span><CardTitle className="mt-1">Hit 100g protein daily</CardTitle><CardDescription className="mt-2">Current target also tracks 2,000 kcal, 2.8L water, and 6-day logging streak.</CardDescription></div>
          <Progress value={82} tone="green" />
          <div className="flex flex-wrap gap-2">
            <Button type="button" onClick={() => openGoal("health")}><Goal className="h-4 w-4" />Set goal</Button>
            <Button type="button" onClick={() => openAgent("Help me set my protein goal")}><Bot className="h-4 w-4" />Ask Agent</Button>
          </div>
        </Card>
        <Card>
          <span className="small-label">AI suggestions</span>
          <CardTitle className="mt-1">Suggested next targets</CardTitle>
          <CardDescription className="mt-2">The agent can suggest targets from your patterns, but accepted or manually entered data becomes the saved goal.</CardDescription>
          <div className="mt-3 grid gap-3">{healthSuggestions.map((item) => <ListItem key={item.title} {...item} badge="Optional" />)}</div>
        </Card>
      </div>
      <Card>
        <CardHeader>
          <div><span className="small-label">Health</span><CardTitle>Health daily summaries</CardTitle><CardDescription>Click a date to see meals, totals, goal progress, and the AI summary.</CardDescription></div>
          <Button type="button" onClick={() => openEntry("meal")}><Plus className="h-4 w-4" />Add meal</Button>
        </CardHeader>
        <div className="grid gap-2">
          {healthSummaries.map((row) => (
            <button className="table-row grid w-full gap-3 rounded-lg border bg-secondary p-3 text-left text-sm hover:border-teal hover:bg-[#fffdfa] max-lg:grid-cols-1" key={row.iso} type="button" onClick={() => openDetail({ domain: "health", date: row.iso })}>
              <strong>{row.date}</strong><span>{row.calories} kcal</span><span>{row.protein}</span><span>{row.meals} meals</span><Badge tone={row.tone}>{row.goal}</Badge><span>{row.summary}</span>
            </button>
          ))}
        </div>
      </Card>
    </ViewFrame>
  );
}
